#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x249B39D24F25E3B6
#
Name     : npth
Version  : 1.6
Release  : 12
URL      : https://gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2
Source0  : https://gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2
Source99 : https://gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2.sig
Summary  : NPTH - the new GNU Portable Threads Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: npth-bin = %{version}-%{release}
Requires: npth-lib = %{version}-%{release}
Requires: npth-license = %{version}-%{release}

%description
NPTH is a cooperative thread library.

%package bin
Summary: bin components for the npth package.
Group: Binaries
Requires: npth-license = %{version}-%{release}

%description bin
bin components for the npth package.


%package dev
Summary: dev components for the npth package.
Group: Development
Requires: npth-lib = %{version}-%{release}
Requires: npth-bin = %{version}-%{release}
Provides: npth-devel = %{version}-%{release}
Requires: npth = %{version}-%{release}

%description dev
dev components for the npth package.


%package lib
Summary: lib components for the npth package.
Group: Libraries
Requires: npth-license = %{version}-%{release}

%description lib
lib components for the npth package.


%package license
Summary: license components for the npth package.
Group: Default

%description license
license components for the npth package.


%prep
%setup -q -n npth-1.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558393012
export GCC_IGNORE_WERROR=1
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1558393012
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/npth
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/npth/COPYING.LIB
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/npth-config

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libnpth.so
/usr/share/aclocal/*.m4

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnpth.so.0
/usr/lib64/libnpth.so.0.1.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/npth/COPYING.LIB
